<<<<<<< HEAD
name: ComputeHive CI/CD Pipeline

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]
  workflow_dispatch:

env:
  DOCKER_REGISTRY: ghcr.io
  DOCKER_IMAGE_PREFIX: ${{ github.repository_owner }}/computehive

jobs:
  # Code Quality Checks
  lint:
    name: Lint Code
    runs-on: ubuntu-latest
    strategy:
      matrix:
        component: [agent, core-services, web, contracts, sdk]
=======
name: ComputeHive CI/CD

on:
  push:
    branches: [ main, develop ]
    tags:
      - 'v*'
  pull_request:
    branches: [ main, develop ]
  workflow_dispatch:

env:
  GO_VERSION: '1.21'
  NODE_VERSION: '20'
  DOCKER_BUILDKIT: 1

jobs:
  # Code quality and security checks
  lint-and-security:
    name: Lint and Security Scan
    runs-on: ubuntu-latest
>>>>>>> 4c40309e804c8f522625b7fd70da67d8d7383849
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Go
<<<<<<< HEAD
        if: matrix.component == 'agent' || matrix.component == 'core-services'
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
          
      - name: Set up Node.js
        if: matrix.component == 'web' || matrix.component == 'contracts' || matrix.component == 'sdk'
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Lint Go Code
        if: matrix.component == 'agent' || matrix.component == 'core-services'
        run: |
          cd ${{ matrix.component }}
          go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
          golangci-lint run --timeout=10m
          
      - name: Lint JavaScript/TypeScript
        if: matrix.component == 'web' || matrix.component == 'sdk'
        run: |
          cd ${{ matrix.component }}
          npm ci
          npm run lint
          
      - name: Lint Solidity
        if: matrix.component == 'contracts'
        run: |
          cd contracts
          npm ci
          npm run lint

  # Unit Tests
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    needs: lint
    strategy:
      matrix:
        component: [agent, core-services, web, contracts, sdk]
    services:
      postgres:
        image: cockroachdb/cockroach:latest-v23.1
        ports:
          - 26257:26257
        options: >-
          --health-cmd "curl -f http://localhost:8080/health"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      redis:
        image: redis:7-alpine
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Go
        if: matrix.component == 'agent' || matrix.component == 'core-services'
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
          
      - name: Set up Node.js
        if: matrix.component == 'web' || matrix.component == 'contracts' || matrix.component == 'sdk'
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Run Go Tests
        if: matrix.component == 'agent' || matrix.component == 'core-services'
        run: |
          cd ${{ matrix.component }}
          go mod download
          go test -v -race -coverprofile=coverage.out -covermode=atomic ./...
          
      - name: Run JavaScript/TypeScript Tests
        if: matrix.component == 'web' || matrix.component == 'sdk'
        run: |
          cd ${{ matrix.component }}
          npm ci
          npm run test:coverage
          
      - name: Run Solidity Tests
        if: matrix.component == 'contracts'
        run: |
          cd contracts
          npm ci
          npm run test:coverage
          
      - name: Upload Coverage
        uses: codecov/codecov-action@v3
        with:
          file: ./${{ matrix.component }}/coverage.out
          flags: ${{ matrix.component }}
          fail_ci_if_error: true

  # Security Scanning
  security:
    name: Security Scan
    runs-on: ubuntu-latest
    needs: test
    permissions:
      security-events: write
    steps:
      - uses: actions/checkout@v4
      
      - name: Run Trivy vulnerability scanner
=======
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
      
      - name: Go Lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
          args: --timeout=10m
          working-directory: ./agent
      
      - name: Go Security Scan
        run: |
          go install github.com/securego/gosec/v2/cmd/gosec@latest
          gosec -severity medium ./...
        working-directory: ./agent
      
      - name: Trivy Security Scan
>>>>>>> 4c40309e804c8f522625b7fd70da67d8d7383849
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          scan-ref: '.'
<<<<<<< HEAD
          format: 'sarif'
          output: 'trivy-results.sarif'
          
      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: 'trivy-results.sarif'
          
      - name: Run Snyk Security Scan
        uses: snyk/actions/golang@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --severity-threshold=high
          
      - name: Run Semgrep
        uses: returntocorp/semgrep-action@v1
        with:
          config: >-
            p/security-audit
            p/secrets
            p/owasp-top-ten
            p/golang
            p/javascript
            p/typescript
            p/smart-contracts

  # Build Docker Images
  build:
    name: Build Docker Images
    runs-on: ubuntu-latest
    needs: [test, security]
    if: github.event_name == 'push'
    strategy:
      matrix:
        service: [agent, auth-service, scheduler-service, marketplace-service, payment-service, telemetry-service]
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.DOCKER_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
=======
          severity: 'CRITICAL,HIGH'
          exit-code: '1'
          ignore-unfixed: true

  # Test Go components
  test-go:
    name: Test Go Components
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        go: ['1.21', '1.22']
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}
      
      - name: Cache Go modules
        uses: actions/cache@v3
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      
      - name: Test Agent
        run: |
          go mod download
          go test -v -race -coverprofile=coverage.out ./...
          go tool cover -html=coverage.out -o coverage.html
        working-directory: ./agent
      
      - name: Test Core Services
        run: |
          go mod download
          go test -v -race -coverprofile=coverage.out ./...
        working-directory: ./core-services
      
      - name: Upload Coverage
        uses: codecov/codecov-action@v3
        with:
          files: ./agent/coverage.out,./core-services/coverage.out
          flags: unittests
          name: codecov-${{ matrix.os }}-go${{ matrix.go }}

  # Test Frontend
  test-frontend:
    name: Test Frontend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          cache-dependency-path: web/dashboard/package-lock.json
      
      - name: Install Dependencies
        run: npm ci
        working-directory: ./web/dashboard
      
      - name: Lint
        run: npm run lint
        working-directory: ./web/dashboard
      
      - name: Test
        run: npm run test:ci
        working-directory: ./web/dashboard
      
      - name: Build
        run: npm run build
        working-directory: ./web/dashboard

  # Test Smart Contracts
  test-contracts:
    name: Test Smart Contracts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
      
      - name: Install Dependencies
        run: npm ci
        working-directory: ./contracts
      
      - name: Compile Contracts
        run: npm run compile
        working-directory: ./contracts
      
      - name: Test Contracts
        run: npm run test
        working-directory: ./contracts
      
      - name: Security Audit
        run: npm audit
        working-directory: ./contracts

  # Build Docker Images
  build-docker:
    name: Build Docker Images
    needs: [lint-and-security, test-go, test-frontend]
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    strategy:
      matrix:
        component:
          - name: agent
            context: ./agent
            dockerfile: ./agent/Dockerfile
          - name: auth-service
            context: ./core-services
            dockerfile: ./core-services/auth-service/Dockerfile
          - name: dashboard
            context: ./web/dashboard
            dockerfile: ./web/dashboard/Dockerfile
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
>>>>>>> 4c40309e804c8f522625b7fd70da67d8d7383849
      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
<<<<<<< HEAD
          images: ${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_IMAGE_PREFIX }}/${{ matrix.service }}
=======
          images: computehive/${{ matrix.component.name }}
>>>>>>> 4c40309e804c8f522625b7fd70da67d8d7383849
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
<<<<<<< HEAD
            type=sha,prefix={{branch}}-
            
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./docker/${{ matrix.service }}.Dockerfile
=======
            type=semver,pattern={{major}}.{{minor}}
            type=sha
      
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ${{ matrix.component.context }}
          file: ${{ matrix.component.dockerfile }}
>>>>>>> 4c40309e804c8f522625b7fd70da67d8d7383849
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

<<<<<<< HEAD
  # Integration Tests
  integration-test:
    name: Integration Tests
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'push' && github.ref == 'refs/heads/develop'
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Kind cluster
        uses: helm/kind-action@v1.8.0
        with:
          cluster_name: computehive-test
          
      - name: Install Istio
        run: |
          curl -L https://istio.io/downloadIstio | ISTIO_VERSION=1.19.0 sh -
          ./istio-1.19.0/bin/istioctl install --set profile=demo -y
          
      - name: Deploy test environment
        run: |
          kubectl create namespace computehive-test
          kubectl label namespace computehive-test istio-injection=enabled
          helm install computehive ./infrastructure/helm/computehive \
            --namespace computehive-test \
            --values ./infrastructure/helm/computehive/values-test.yaml \
            --wait
            
      - name: Run integration tests
        run: |
          cd tests/integration
          npm ci
          npm run test
          
      - name: Collect logs on failure
        if: failure()
        run: |
          kubectl logs -n computehive-test -l app=auth-service --tail=100
          kubectl logs -n computehive-test -l app=scheduler-service --tail=100
          kubectl describe pods -n computehive-test
=======
  # Build Binaries
  build-binaries:
    name: Build Binaries
    needs: [lint-and-security, test-go]
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    strategy:
      matrix:
        include:
          - os: linux
            arch: amd64
          - os: linux
            arch: arm64
          - os: darwin
            arch: amd64
          - os: darwin
            arch: arm64
          - os: windows
            arch: amd64
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
      
      - name: Build Binary
        env:
          GOOS: ${{ matrix.os }}
          GOARCH: ${{ matrix.arch }}
        run: |
          output_name="computehive-agent-${{ matrix.os }}-${{ matrix.arch }}"
          if [ "${{ matrix.os }}" = "windows" ]; then
            output_name="${output_name}.exe"
          fi
          CGO_ENABLED=0 go build -ldflags="-s -w -X main.version=${{ github.ref_name }}" -o "../bin/${output_name}" ./cmd/agent
        working-directory: ./agent
      
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: binaries
          path: bin/*
>>>>>>> 4c40309e804c8f522625b7fd70da67d8d7383849

  # Deploy to Staging
  deploy-staging:
    name: Deploy to Staging
<<<<<<< HEAD
    runs-on: ubuntu-latest
    needs: [build, integration-test]
    if: github.event_name == 'push' && github.ref == 'refs/heads/develop'
    environment:
      name: staging
      url: https://staging.computehive.io
    steps:
      - uses: actions/checkout@v4
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
          
      - name: Update kubeconfig
        run: |
          aws eks update-kubeconfig --name computehive-staging --region us-east-1
          
      - name: Deploy with Helm
        run: |
          helm upgrade --install computehive ./infrastructure/helm/computehive \
            --namespace computehive \
            --values ./infrastructure/helm/computehive/values-staging.yaml \
            --set-string global.image.tag=${{ github.sha }} \
            --wait \
            --timeout 10m
            
      - name: Run smoke tests
        run: |
          cd tests/smoke
          npm ci
          ENVIRONMENT=staging npm run test
=======
    needs: [build-docker]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/develop'
    environment: staging
    steps:
      - uses: actions/checkout@v4
      
      - name: Deploy to Kubernetes
        run: |
          echo "Deploying to staging..."
          # kubectl apply -f infrastructure/kubernetes/staging/
>>>>>>> 4c40309e804c8f522625b7fd70da67d8d7383849

  # Deploy to Production
  deploy-production:
    name: Deploy to Production
<<<<<<< HEAD
    runs-on: ubuntu-latest
    needs: deploy-staging
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    environment:
      name: production
      url: https://computehive.io
    steps:
      - uses: actions/checkout@v4
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.PROD_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.PROD_AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
          
      - name: Update kubeconfig
        run: |
          aws eks update-kubeconfig --name computehive-prod --region us-east-1
          
      - name: Deploy with Helm (Canary)
        run: |
          helm upgrade --install computehive-canary ./infrastructure/helm/computehive \
            --namespace computehive \
            --values ./infrastructure/helm/computehive/values-production.yaml \
            --values ./infrastructure/helm/computehive/values-canary.yaml \
            --set-string global.image.tag=${{ github.sha }} \
            --wait \
            --timeout 10m
            
      - name: Run canary tests
        run: |
          cd tests/canary
          npm ci
          ENVIRONMENT=production npm run test
          
      - name: Promote to full production
        if: success()
        run: |
          helm upgrade --install computehive ./infrastructure/helm/computehive \
            --namespace computehive \
            --values ./infrastructure/helm/computehive/values-production.yaml \
            --set-string global.image.tag=${{ github.sha }} \
            --wait \
            --timeout 15m
            
      - name: Rollback on failure
        if: failure()
        run: |
          helm rollback computehive -n computehive

  # Performance Tests
  performance-test:
    name: Performance Tests
    runs-on: ubuntu-latest
    needs: deploy-staging
    if: github.event_name == 'push' && github.ref == 'refs/heads/develop'
    steps:
      - uses: actions/checkout@v4
      
      - name: Run k6 performance tests
        uses: grafana/k6-action@v0.3.0
        with:
          filename: tests/performance/load-test.js
          cloud: true
        env:
          K6_CLOUD_TOKEN: ${{ secrets.K6_CLOUD_TOKEN }}
          K6_CLOUD_PROJECT_ID: ${{ secrets.K6_CLOUD_PROJECT_ID }}
          
      - name: Check performance thresholds
        run: |
          # Check if performance meets SLA requirements
          # This would typically parse k6 results and compare against thresholds 
=======
    needs: [build-docker]
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    environment: production
    steps:
      - uses: actions/checkout@v4
      
      - name: Deploy to Kubernetes
        run: |
          echo "Deploying to production..."
          # kubectl apply -f infrastructure/kubernetes/production/

  # Create Release
  create-release:
    name: Create Release
    needs: [build-binaries]
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - uses: actions/checkout@v4
      
      - name: Download Binaries
        uses: actions/download-artifact@v3
        with:
          name: binaries
          path: bin/
      
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: bin/*
          draft: false
          prerelease: false
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
>>>>>>> 4c40309e804c8f522625b7fd70da67d8d7383849
